server:
  port: 8085
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/exchange_test_a?useUnicode=true&characterEncoding=utf8
        username: root
        password: root


mybatis:
  type-aliases-package: com.wyc.exchange.dto
  config-location: classpath:mybatis-config.xml

